name: CI

on:
  pull_request:
    branches:
      - main
      - develop
      - master
  push:
    branches:
      - main
      - develop
      - master

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

  lint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    needs: install
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        working-directory: client
        run: npm run lint

  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    needs: install
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Typecheck client
        working-directory: client
        run: npx tsc --noEmit

      - name: Typecheck backend
        working-directory: backend
        run: |
          if [ -f "tsconfig.json" ]; then
            npx tsc --noEmit
          else
            echo "No tsconfig.json found in backend, skipping typecheck"
          fi

  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        working-directory: client
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: client/.next
          retention-days: 1

  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: install
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests
        working-directory: backend
        run: npm test
        continue-on-error: false

  ci-success:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, typecheck, build, test-backend]
    if: success()
    
    steps:
      - name: All CI checks passed
        run: echo "✅ All CI checks passed successfully!"

